config/routes.rb
RubySpline::Application.routes.draw do
  resources :dikshas

  resources :posts

  get "home/index"
  get "posts/new"
  get "post/show"

    root :to => "home#index"
match '/new', :to => 'posts#new'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
end

app/models/diksha.rb
class Diksha < ActiveRecord::Base
end

app/models/post.rb
class Post < ActiveRecord::Base
validates :name,  :presence => true
  validates :title, :presence => true,
                    :length => { :minimum => 5 }
                    has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.create(params[:comment])
    redirect_to post_path(@post)
  end
end

app/controllers/dikshas_controller.rb
class DikshasController < ApplicationController
  # GET /dikshas
  # GET /dikshas.xml
  def index
    @dikshas = Diksha.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @dikshas }
    end
  end

  # GET /dikshas/1
  # GET /dikshas/1.xml
  def show
    @diksha = Diksha.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @diksha }
    end
  end

  # GET /dikshas/new
  # GET /dikshas/new.xml
  def new
    @diksha = Diksha.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @diksha }
    end
  end

  # GET /dikshas/1/edit
  def edit
    @diksha = Diksha.find(params[:id])
  end

  # POST /dikshas
  # POST /dikshas.xml
  def create
    @diksha = Diksha.new(params[:diksha])

    respond_to do |format|
      if @diksha.save
        format.html { redirect_to(@diksha, :notice => 'Diksha was successfully created.') }
        format.xml  { render :xml => @diksha, :status => :created, :location => @diksha }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @diksha.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /dikshas/1
  # PUT /dikshas/1.xml
  def update
    @diksha = Diksha.find(params[:id])

    respond_to do |format|
      if @diksha.update_attributes(params[:diksha])
        format.html { redirect_to(@diksha, :notice => 'Diksha was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @diksha.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /dikshas/1
  # DELETE /dikshas/1.xml
  def new_fn
  	@diksha= Diksha.new(params[:diksha])
  	respond_to do |format|
      format.html { redirect_to(dikshas_url) }
      format.xml  { head :ok }
      end	
  end
  def destroy
    @diksha = Diksha.find(params[:id])
    @diksha.destroy

    respond_to do |format|
      format.html { redirect_to(dikshas_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    if @posts = Post.create(params[:post])
  # success
  end
end

end

app/controllers/new_controller_controller.rb
class NewControllerController < ApplicationController
	def more
	end

end

app/controllers/newcontroller_controller.rb
class NewcontrollerController < ApplicationController
	def hello
	end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  # GET /posts
  # GET /posts.xml
  def index
    @posts = Post.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @posts }
    end
  end

  # GET /posts/1
  # GET /posts/1.xml
  def show
    @post = Post.find(:all)

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @post }
    end

  end

  # GET /posts/new
  # GET /posts/new.xml
  def new
   if @posts = Post.create(params[:post])
  # success
  end
    @post = Post.new
    @post1 = Post.find(:all,   :order => 'name ASC',)

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @post }
      format.xml  { render :xml => @post1 }
    end
  end

  # GET /posts/1/edit
  def edit

     @post = Post.find(params[:id])
  end

  # POST /posts
  # POST /posts.xml
  def create
    @post = Post.new(params[:post])
  #  @post=params[:varliable_test]

    respond_to do |format|
      if @post.save
        format.html { redirect_to(@post, :notice => 'Post was successfully created.') }
        format.xml  { render :xml => @post, :status => :created, :location => @post }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @post.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /posts/1
  # PUT /posts/1.xml
  def update
    @post = Post.find(params[:id])

    respond_to do |format|
      if @post.update_attributes(params[:post])
        format.html { redirect_to(@post, :notice => 'Post was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @post.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.xml
  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    respond_to do |format|
      format.html { redirect_to(new_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/dikshas_helper.rb
module DikshasHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/new_controller_helper.rb
module NewControllerHelper
end

app/helpers/newcontroller_helper.rb
module NewcontrollerHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/dikshas/_form.html.erb
<%= form_for(@diksha) do |f| %>
  <% if @diksha.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@diksha.errors.count, "error") %> prohibited this diksha from being saved:</h2>

      <ul>
      <% @diksha.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/dikshas/edit.html.erb
<h1>Editing diksha</h1>

<%= render 'form' %>

<%= link_to 'Show', @diksha %> |
<%= link_to 'Back', dikshas_path %>

app/views/dikshas/index.html.erb
<h1>Listing dikshas</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @dikshas.each do |diksha| %>
  <tr>
    <td><%= link_to 'Show', diksha %></td>
    <td><%= link_to 'Edit', edit_diksha_path(diksha) %></td>
    <td><%= link_to 'Destroy', diksha, :confirm => 'Are you sure?', :method => :delete %></td>
    <td><%= link_to 'Showqwqw',new_fn_diksha_path %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Diksha', new_diksha_path %>

app/views/dikshas/new.html.erb
<h1>New diksha</h1>

<%= render 'form' %>

<%= link_to 'Back', dikshas_path %>

app/views/dikshas/new_fn.html.erb
<h1>New diksha</h1>
<p>
sakjhdakhkdhakdhask
</p>

app/views/dikshas/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_diksha_path(@diksha) %> |
<%= link_to 'Back', dikshas_path %>

app/views/home/index.html.erb
<h1>Helo rails</h1>
<%= link_to "My Blog", posts_path %>

<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/_table.html.erb
<div id="new2" style="width:360px;height:355px;background-color:#E5DBDB;position:fixed;right:320px;top:420px" >
<h4 align='center' style="background-color:black; color:white">List of the Powerpoint Slides</h4>
<div id="new3" style="overflow:auto;width:355px;height:220px;padding:0px; margin-left:3px"">
<table style="overflow:auto;cell-padding:10px;padding:30px;width:400px;font-family:arial;background-color:white;font-size:10pt; ">
<tr><td  onMouseOver="imageS(1)" onclick="change(30,1)">Introduction</td></tr>
<tr><td style="margin-left:100px;background-color:#D8D4D4;" onMouseOver="imageS(2)" onclick="change(50,2)">The elephant in the room</td></tr>
<tr><td  onMouseOver="imageS(3)" onclick="change(60,3)">I am not in denial</td></tr>
<tr><td style="background-color:#D8D4D4;" onMouseOver="imageS(4)" onclick="change(70,4)">What we are not talking about</td></tr>
<tr><td  onMouseOver="imageS(5)">Today’s Talk</td></tr>
<tr><td style="background-color:#D8D4D4;" onMouseOver="imageS(6)" onclick="change(30,1)">My Childhood Dreams</td></tr>
<tr><td style="text-align:center" onMouseOver="imageS(7)">Image 1</td></tr>
<tr><td style="background-color:#D8D4D4;text-align:center;" onMouseOver="imageS(8)">Image 2</td></tr>
<tr><td style="text-align:center" onMouseOver="imageS(9)">Image 3</td></tr>
<tr><td style="background-color:#D8D4D4;text-align:center;" onMouseOver="imageS(10)">Image 4</td></tr>
<tr><td style="text-align:center" onMouseOver="imageS(11)">Image 5</td></tr>
<tr><td style="background-color:#D8D4D4;text-align:center;" onMouseOver="imageS(12)"">Image 6 </td></tr>
<tr><td  onMouseOver="imageS(13)">My Childhood Dreams-The List</td></tr>
<tr><td style="background-color:#D8D4D4;" onMouseOver="imageS(14)">i)Being in zero gravity</td></tr>
<tr><td style="text-align:center" onMouseOver="imageS(15)">Image</td></tr>
<tr><td style="background-color:#D8D4D4;text-align:center;" onMouseOver="imageS(16)">The vomit comet</td></tr>
<tr><td style="text-align:center;margin-left:20px;" onMouseOver="imageS(17)">Brick walls are there for a reason</td></tr>
<tr><td style="background-color:#D8D4D4;text-align:center;" onMouseOver="imageS(18)">Image 1</td></tr>
<tr><td style="text-align:center" onMouseOver="imageS(19)">Image 2</td></tr>
<tr><td style="background-color:#D8D4D4;" onMouseOver="imageS(20)">ii)Making it to NFL-Football</td></tr>
<tr><td style="text-align:center" onMouseOver="imageS(21)" >I Never Made it to the NFL</td></tr>
<tr><td style="background-color:#D8D4D4;" onMouseOver="imageS(22)">iii)Being an author in the World Book Encyclopedia</td></tr>
<tr><td style="text-align:center" onMouseOver="imageS(23)">Image 1</td></tr>
<tr><td style="background-color:#D8D4D4;text-align:center;" onMouseOver="imageS(24)">Image 2</td></tr>
<tr><td  onMouseOver="imageS(25)">iv)Meeting Captain Kirk</td></tr>
<tr><td style="background-color:#D8D4D4;text-align:center;" onMouseOver="imageS(26)">Dream</td></tr>
<tr><td style="text-align:center" onMouseOver="imageS(27)">Image 1</td></tr>
<tr><td style="background-color:#D8D4D4;text-align:center;" onMouseOver="imageS(28)">Image 2</td></tr>
<tr><td style="text-align:center" onMouseOver="imageS(29)">Image 3</td></tr>
<tr><td style="background-color:#D8D4D4;text-align:center;" onMouseOver="imageS(30)">Image 4</td></tr>
<tr><td  onMouseOver="imageS(31)">v)Winning STuffed Toys</td></tr>
<tr><td style="background-color:#D8D4D4;text-align:center;" onMouseOver="imageS(32)">Image 1</td></tr>
<tr><td style="text-align:center" onMouseOver="imageS(34)">Image 2</td></tr>
<tr><td style="background-color:#D8D4D4;text-align:center;" onMouseOver="imageS(35)">Image 3</td></tr>
<tr><td style="text-align:center" onMouseOver="imageS(36)">Image 4</td></tr>
<tr><td style="background-color:#D8D4D4;text-align:center;" onMouseOver="imageS(37)">Image 5</td></tr>
<tr><td style="text-align:center" onMouseOver="imageS(38)">Image 6</td></tr>
<tr><td style="background-color:#D8D4D4;text-align:center;" onMouseOver="imageS(39)">I can hear the cynics</td></tr>
<tr><td  onMouseOver="imageS(40)">vi)Being an Imagineer</td></tr>
<tr><td style="background-color:#D8D4D4;text-align:center;" onMouseOver="imageS(41)">Image 1</td></tr>
<tr><td style="text-align:center" onMouseOver="imageS(42)">Image 2</td></tr>
<tr><td style="background-color:#D8D4D4;text-align:center;" onMouseOver="imageS(43)">Image 3</td></tr>
<tr><td style="text-align:center" onMouseOver="imageS(44)">Image 4</td></tr>
<tr><td style="background-color:#D8D4D4;text-align:center;" onMouseOver="imageS(45)">1991:VR on Five Dollars a Day</td></tr>
<tr><td style="text-align:center" onMouseOver="imageS(46)">Imagineering</td></tr>
<tr><td style="background-color:#D8D4D4;text-align:center;" onMouseOver="imageS(47)">Image</td></tr>
<tr><td style="text-align:center" onMouseOver="imageS(48)">Introduction</td></tr>
<tr><td style="background-color:#D8D4D4;text-align:center;" onMouseOver="imageS(49)">Jon Snoddy</td></tr>
<tr><td style="text-align:center" onMouseOver="imageS(50)">Image 1</td></tr>
<tr><td style="background-color:#D8D4D4;text-align:center;" onMouseOver="imageS(51)">Image 2</td></tr>
<tr><td style="text-align:center" onMouseOver="imageS(52)">Alladin Image</td></tr>
<tr><td style="background-color:#D8D4D4;text-align:center;" onMouseOver="imageS(53)">Image 1</td></tr>
<tr><td style="text-align:center" onMouseOver="imageS(54)">Image 2</td></tr>
<tr><td style="background-color:#D8D4D4;text-align:center;" onMouseOver="imageS(55)">Image 3</td></tr>
<tr><td style="text-align:center" onMouseOver="imageS(56)">Image 4</td></tr>
<tr><td style="background-color:#D8D4D4;text-align:center;" onMouseOver="imageS(57)">Charlie and the Chocolate Factory</td></tr>
<tr><td style="text-align:center" onMouseOver="imageS(58)">Working on Aladdin VR</td></tr>
<tr><td style="background-color:#D8D4D4;text-align:center;" onMouseOver="imageS(59)">Really being an Imagineer</td></tr>
<tr><td style="text-align:center" onMouseOver="imageS(60)">Image</td></tr>
<tr><td style="background-color:#D8D4D4;" onMouseOver="imageS(61)">Virtual Jungle Cruise</td></tr>
<tr><td style="text-align:center" onMouseOver="imageS(62)">Image</td></tr>
<tr><td style="background-color:#D8D4D4;" onMouseOver="imageS(63)">Enabling the Childhood Dreams of Others</td></tr>
<tr><td style="text-align:center" onMouseOver="imageS(64)">Image 1</td></tr>
<tr><td style="background-color:#D8D4D4;text-align:center;" onMouseOver="imageS(65)">Image 2</td></tr>
<tr><td  onMouseOver="imageS(66)">Building Virtual Worlds</td></tr>
<tr><td style="background-color:#D8D4D4;text-align:center;" onMouseOver="imageS(67)">The First Year</td></tr>
<tr><td style="text-align:center" onMouseOver="imageS(68)">Campus-wide Exhibition</td></tr>
<tr><td style="background-color:#D8D4D4;text-align:center;" onMouseOver="imageS(69)">Image 1</td></tr>
<tr><td style="text-align:center" onMouseOver="imageS(70)">Image 3</td></tr>
<tr><td style="background-color:#D8D4D4;text-align:center;" onMouseOver="imageS(71)">Image 4</td></tr>
<tr><td style="text-align:center" onMouseOver="imageS(72)">Image 5</td></tr>
<tr><td style="background-color:#D8D4D4;text-align:center;" onMouseOver="imageS(73)">Image 6</td></tr>
<tr><td style="text-align:center" onMouseOver="imageS(74)">Image 7</td></tr>
<tr><td style="background-color:#D8D4D4;text-align:center;" onMouseOver="imageS(75)">Image 8</td></tr>
<tr><td style="text-align:center" onMouseOver="imageS(76)">Image 9</td></tr>
<tr><td style="background-color:#D8D4D4;text-align:center;" onMouseOver="imageS(77)">Image 10</td></tr>
<tr><td style="text-align:center" onMouseOver="imageS(78)">Image 11</td></tr>
<tr><td style="background-color:#D8D4D4;text-align:center;" onMouseOver="imageS(79)">Image 12</td></tr>
<tr><td style="text-align:center" onMouseOver="imageS(80)">Image 13</td></tr>
<tr><td style="background-color:#D8D4D4;text-align:center;" onMouseOver="imageS(81)">Image 14</td></tr>
<tr><td style="text-align:center" onMouseOver="imageS(82)">Image 15</td></tr>
<tr><td style="background-color:#D8D4D4;text-align:center;" onMouseOver="imageS(83)">Image 16</td></tr>
<tr><td style="text-align:center" onMouseOver="imageS(84)">BVW was a pioneering course</td></tr>
<tr><td style="background-color:#D8D4D4;text-align:center;" onMouseOver="imageS(85)">Image</td></tr>
<tr><td  onMouseOver="imageS(86)">The Dream Fulfillment Factory</td></tr>
<tr><td style="background-color:#D8D4D4;text-align:center;" onMouseOver="imageS(87)">Entertainment Technology Center (ETC)</td></tr>
<tr><td style="text-align:center" onMouseOver="imageS(88)">Right Brain / Left Brain</td></tr>
<tr><td style="background-color:#D8D4D4;text-align:center;" onMouseOver="imageS(89)">Don & I shared an office for six years</td></tr>
<tr><td style="text-align:center" onMouseOver="imageS(90)">Co-Director Credit for the ETC is Success</td></tr>
<tr><td style="background-color:#D8D4D4;text-align:center;" onMouseOver="imageS(91)">The ETC is to masters degrees as Cirque Du Soleil is to circus</td></tr>
<tr><td style="text-align:center" onMouseOver="imageS(92)">ETC Curriculum: First Draft</td></tr>
<tr><td style="background-color:#D8D4D4;text-align:center;" onMouseOver="imageS(93)">ETC Curriculum</td></tr>
<tr><td style="text-align:center" onMouseOver="imageS(94)">Key to the ETC is Success: Freedom</td></tr>
<tr><td style="background-color:#D8D4D4;text-align:center;" onMouseOver="imageS(95)">Edutainment</td></tr>
<tr><td style="text-align:center" onMouseOver="imageS(96)">Companies guaranteed hiring our students</td></tr>
</table>
</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
<!! Adding Shadow Element to the Center- Content box of the Home Page -->
  <style>
    	shadow {
      -moz-box-shadow: 0 0 30px 5px #999;
      -webkit-box-shadow: 0 0 30px 5px #999;
      }
</style>
  <title >DNS Player</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
  <%= javascript_include_tag 'swfobject' %>
  <%= javascript_include_tag 'flowplayer-3.2.6.min' %>
  <%= javascript_include_tag 'menuView' %>

</head><!-- Exiting Head Tag -->
<body onLoad="hide1()"><!-- Beginning of Body Tag -->
<div style="overflow:auto;height=100px;" >

	<div  id="box" ><!-- Using div tag to create a box-like element with id=box -->
<!-- Creating a Div box which stores the properties of the header part which includes the Main heading(ie DNS PLAYER) and a Top Menu Bar(id=list-nav-->
		<div id="title" >
			<ul class=titlemenu style="float:right;">
			  <li><a class=button href="login.html"><span>Login</span></a></li>
			  <li><a class=button href="about.html"><span>About</span></a></li>
			  <li><a class=button href="http://www.gmail.com"><span>Register</span></a></li>
			</ul>
			<h1>DNS PLAYER</h1>
			<p>Where need meets results......</p>
		</div>
<br>
<!-- Creating a Div Panel which includes 2 Div attributes. One is for taking care of the left naviagation bar and the other one for Storing the 		welcome contents -->
		<div id="workspace" style="width:200px;float:left;">
		<ul class="hovermenu" style="list-style:none;text-decoration:none;">
		<!-- Creating 2 buttons- Home and Video. On click of Video, @ addtional options appear-ADD BOOKMARK and SHOW BOOKMARK and 					another Div tag opens up which shall act as the panel for the video ------------------->
		  	    <li><button style="border:0;background:none;padding:0;margin:0; color:gray; font-weight:bold; font-size:16px" onclick="hide0()">Home</button></li>
		  	    <li><button style="border:0;background:none;padding:0;margin:0; color:gray;font-weight:bold; font-size:16px" onclick="hide1()">Video</button>
		  	    	<ul id="new"   style="display:none;" >
		            		<li><button style="border:0;background:none;padding:0;margin:0;color:gray;" onclick="hide2()">Add Bookmark</button>
		            		<!-- Hidden Box for Panel to contain Video evoked on click of Video Button linking it to Flow Player----------->
			 		<div class="hidden" id="leftmenu" style="position:fixed;top:145px;right:5px;margin-		        left:200px;float:right;width:300px;height:300px;border:1px #ba0202;"><%= render 'posts/show' %></div>
	       		    		</li>
 		 	    	<li><a href="about.html" style="color:gray;">Show Bookmark</a></li>
				</ul>
				<!--</div>-->
 			     </li>
 			     <!-- Youtube Video Player evoked on click of 'Youtube' Button -->
 			     <li><button style="border:0;background:none;padding:0;margin:0;color:gray;font-weight:bold; font-size:16px" onclick="hide3()">Youtube</button></li>
 			     <li><button style="border:0;background:none;padding:0;margin:0;color:gray;font-weight:bold; font-size:16px" onclick="hide4()">ppt</button></li>
		</ul>
		</div>
				<!--<div class="hidden" id="new"   style="display:none;float:right;">-->
				<div  id="new1" style="display:none;position:fixed;top:100px;right:500px;width:600px;border:1px #ba0202;">	<%= yield %>
				<div >
<!---->





<!--<iframe src="https://docs.google.com/present/view?id=0AUnWV2Qln9zkZGZwMzY0NHhfMGZidm00N2Rm&hl=en_GB" width="500px" height="500px"></iframe>-->
<img style="position:fixed;top:100px;right:320px;width:360px;border:1px #ba0202;" src="/images/pausch/img0.gif" id="imageSource" >
<%= render 'layouts/table' %>









</div>
				</div>

<!-- DIV tag for containing the welcome text on the Screen Image -->
		<div class="shadow">
		<div id="content" style="width:800px;height:300px;float:left;border:1px solid #ba0202;padding:0;margin-left:30px;">&#160;&#160;&#160;

			<h1 align="center" >Welcome to DNS Player</h1>
			<p align="left">A one-stop solution for playing youtube videos on the Net!! As you will see, the procedure is very simple.All you need to do is past the URL of the desired video and leave the rest to us. You also have the feature of bookmarking certain part's of the video and then later playing the video from those specific parts itself.Sounds good? Well click on the Video Link in the Menu on the left and proceed.</p><br><br><p align="center">Thanks for visiting!!</p>
		</div>
		</div>
				<!-- Creating text area for the user to enter his/her desired YouTube video URL -->
		<div id="youtube" style="display:none">
		<input type="text" size="30" name="url1" id="url1" />
		<input type="button" value="Url" onclick="Url()" />
		<iframe width="560" height="349" frameborder="0" allowfullscreen id="src1"></iframe></div>

<div id="ppt">


<iframe src="https://docs.google.com/present/view?id=0AUnWV2Qln9zkZGZwMzY0NHhfMGZidm00N2Rm&hl=en_GB" width="500px" height="500px"></iframe>
</div>

</div>
</body>
</html>

app/views/new_controller/index.html.erb
<h1> this is the new controller</h1>

app/views/newcontroller/hello.html.erb
<h1>hello world</h1>
<p>dkahkdhakhdka</p>
<table>
<tr>
<td>dadas</td>
<td>dadas</td>
<td>dadas</td>
<td>dadas</td>
</tr>
<tr>
<td>dadas</td>
<td>dadas</td>
<td>dadas</td>
</tr>
</table>

app/views/posts/_form.html.erb
<!--

<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="actions">
    <%= f.submit %>

  </div>
<% end %>

-->
<form action="/people" class="new_person" id="new_person" method="post">
  <div style="margin:0;padding:0;display:inline">
    <input name="authenticity_token" type="hidden" value="NrOp5bsjoLRuK8IW5+dQEYjKGUJDe7TQoZVvq95Wteg=" />
  </div>
  <label for="person_first_name">First name</label>:
  <input id="person_first_name" name="person[first_name]" size="30" type="text" id="hello"/><br />

  <label for="person_last_name">Last name</label>:
  <input id="person_last_name" name="person[last_name]" size="30" type="text" /><br />

  <input id="person_submit" name="commit" type="submit" value="Create Person" />
</form>

app/views/posts/_show.html.erb
	<!--Displays the topics-->

	<%= @post1.each do |post1|%>


  <input type="button" value= "<%= post1.title %>" onclick="change('<%=post1.name%>','<%=post1.id%>')"/>
<!--Deletes the given record from the table-->
<%= link_to 'Destroy', post1, :confirm => 'Are you sure?', :method => :delete %>
<br />
<% end %>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<h1>Listing posts</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Title</th>
    <th>sUP</th>
    <th>dwhdied</th>
    <th>fhdskfhd</th>
  </tr>

<% @posts.each do |post| %>
  <tr>
    <td><%= post.name %></td>
    <td><%= post.title %></td>
    <td><%= link_to 'Show', post %></td>
    <td><%= link_to 'Edit', edit_post_path(post) %></td>
    <td><%= link_to 'Destroy', post, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />
hey i am chumma adding stuf into it..:)):)

<%= link_to 'New Post', new_post_path %>